services:

  mc:
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: mc
    env_file:
      - ../.env
    volumes:
    #  - ../:/app
      - ../plugins:/app/plugins
      - ../server.properties:/app/server.properties
      - $SERVERDIR/worlds:/app/worldsc
      - $SERVERDIR/bluemap:/app/bluemap
    ports:
      - $GAME_PORT:25565
      - $RCON_PORT:25575
      - $BLUEMAP_PORT:8100
      - $DYNMAP_PORT:8123
