version: "3.7"

services:

  mc:
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: mc
    env_file:
      - ../.env
    volumes:
    #  - ../:/app
      - ../plugins:/app/plugins
      - ../eula.txt:/app/eula.txt
      - ../server.properties:/app/server.properties
      - $SERVERDIR:/app/worlds
    ports:
      - $GAME_PORT:25565
      - $RCON_PORT:25575
      - $DYNMAP_PORT:8123
